from scrapy.item import Field, Item

class MadridItem(Item):
    titulo = Field()
    fecha_convocatoria = Field()
    estado = Field()
    fecha_fin_presentacion = Field()
    estado_de_la_licitacion = Field()
    tipo_publicacion = Field()
    objeto_del_contrato = Field()
    codigo_cpv = Field()
    compra_publica_innovadora = Field()
    numero_de_expediente = Field()
    referencia = Field()
    tipo_de_contrato = Field()
    entidad_adjudicadora = Field()
    codigo_nuts = Field()
    procedimiento_adjudicacion = Field()
    valor_estimado_sin_i_v_a = Field()
    presupuesto_base_licitacion_sin_impuestos = Field()
    presupuesto_base_licitacion_importe_total = Field()
    duracion_del_contrato = Field()
    adjudicacion_del_contrato_publicada_el = Field()
    formalizacion_del_contrato_publicada_el = Field()
    formalizacion_del_contrato_publicada_en_bocm_el = Field()
    resultado_adjudicacion = Field()
    fecha_comunicacion_previa_a_la_comision_europea_al_b_o_e_y_al_b_o_c_m = Field()
    tipo_resolucion = Field()
    fecha_limite_de_presentacion_de_ofertas_o_solicitudes_de_participacion = Field()
    fecha_publicacion_de_la_licitacion_en_el_BOCM = Field()
    puntos_de_informacion = Field()
    empresarios_excluidos_publicados_el = Field()
    defectos_u_omisiones_de_la_documentacion_publicados_el = Field()
    otras_informaciones_publicadas_el = Field()
    desistimiento_del_contrato_publicado_el = Field()
    fecha_publicacion_de_la_licitacion_en_el_bocm = Field()
    ofertas_anormales_o_desproporcionadas_publicadas_el = Field()

class AdjudicacionMadridItem(Item):
    nolote = Field()
    noofertas = Field()
    resultado = Field()
    nif_adjudicatario = Field()
    nombre_o_razon_social_adjudicatario = Field()
    importe_adjudicacion_sin_iva = Field()
    importe_adjudicacion_con_iva = Field()
